Add genome attribs column metadata model
```python
In [1]: import src.common.product_models.columnar_attribs_common_models
as m

In [2]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.INT,
   ...:         )
   ...:     ]
   ...: )
Out[2]: ColumnarAttributesMeta(columns=[AttributesColumn(key='foo',
type=<ColumnType.INT: 'int'>, filter_strategy=None, min_value=None,
max_value=None, enum_values=None)])

In [3]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.DATE,
   ...:             min_value="2023-08-25T22:08:33.189+0000",
   ...:             max_value="2023-08-25T22:08:33.189+0000ZZZ"
   ...:         )
   ...:     ]
   ...: )
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call
last)
Cell In[3], line 3
      1 m.ColumnarAttributesMeta(
      2     columns=[
----> 3         m.AttributesColumn(
      4             key="foo",
      5             type=m.ColumnType.DATE,
      6             min_value="2023-08-25T22:08:33.189+0000",
      7             max_value="2023-08-25T22:08:33.189+0000ZZZ"
      8         )
      9     ]
     10 )

File ~/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/pydantic/main.py:165,
in BaseModel.__init__(__pydantic_self__, **data)
    163 # `__tracebackhide__` tells pytest and some other tools to omit
this function from tracebacks
    164 __tracebackhide__ = True
--> 165 __pydantic_self__.__pydantic_validator__.validate_python(data,
self_instance=__pydantic_self__)

ValidationError: 1 validation error for AttributesColumn
max_value
  Value error, max_value is not a valid ISO8601 date:
2023-08-25T22:08:33.189+0000ZZZ [type=value_error,
input_value='2023-08-25T22:08:33.189+0000ZZZ', input_type=str]
    For further information visit
https://errors.pydantic.dev/2.3/v/value_error

In [4]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.DATE,
   ...:             min_value="2023-08-25T22:08:33.189+0000",
   ...:             max_value="2023-08-25T22:08:33.189+0000"
   ...:         )
   ...:     ]
   ...: )
Out[4]: ColumnarAttributesMeta(columns=[AttributesColumn(key='foo',
type=<ColumnType.DATE: 'date'>, filter_strategy=None,
min_value='2023-08-25T22:08:33.189+0000',
max_value='2023-08-25T22:08:33.189+0000', enum_values=None)])

In [5]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.STRING
   ...:         )
   ...:     ]
   ...: )
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call
last)
Cell In[5], line 3
      1 m.ColumnarAttributesMeta(
      2     columns=[
----> 3         m.AttributesColumn(
      4             key="foo",
      5             type=m.ColumnType.STRING
      6         )
      7     ]
      8 )

File ~/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/pydantic/main.py:165,
in BaseModel.__init__(__pydantic_self__, **data)
    163 # `__tracebackhide__` tells pytest and some other tools to omit
this function from tracebacks
    164 __tracebackhide__ = True
--> 165 __pydantic_self__.__pydantic_validator__.validate_python(data,
self_instance=__pydantic_self__)

ValidationError: 1 validation error for AttributesColumn
  Value error, String types require a filter strategy [type=value_error,
input_value={'key': 'foo', 'type': <C...nType.STRING: 'string'>},
input_type=dict]
    For further information visit
https://errors.pydantic.dev/2.3/v/value_error

In [7]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.STRING,
   ...:             filter_strategy=m.FilterStrategy.FULL_TEXT
   ...:         )
   ...:     ]
   ...: )
Out[7]: ColumnarAttributesMeta(columns=[AttributesColumn(key='foo',
type=<ColumnType.STRING: 'string'>,
filter_strategy=<FilterStrategy.FULL_TEXT: 'fulltext'>, min_value=None,
max_value=None, enum_values=None)])

In [8]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.INT,
   ...:             filter_strategy=m.FilterStrategy.FULL_TEXT
   ...:         )
   ...:     ]
   ...: )
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call
last)
Cell In[8], line 3
      1 m.ColumnarAttributesMeta(
      2     columns=[
----> 3         m.AttributesColumn(
      4             key="foo",
      5             type=m.ColumnType.INT,
      6             filter_strategy=m.FilterStrategy.FULL_TEXT
      7         )
      8     ]
      9 )

File ~/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/pydantic/main.py:165,
in BaseModel.__init__(__pydantic_self__, **data)
    163 # `__tracebackhide__` tells pytest and some other tools to omit
this function from tracebacks
    164 __tracebackhide__ = True
--> 165 __pydantic_self__.__pydantic_validator__.validate_python(data,
self_instance=__pydantic_self__)

ValidationError: 1 validation error for AttributesColumn
  Value error, Only string types may have a filter strategy
[type=value_error, input_value={'key': 'foo', 'type': <C....FULL_TEXT:
'fulltext'>}, input_type=dict]
    For further information visit
https://errors.pydantic.dev/2.3/v/value_error

In [9]: m.ColumnarAttributesMeta(
   ...:     columns=[
   ...:         m.AttributesColumn(
   ...:             key="foo",
   ...:             type=m.ColumnType.ENUM,
   ...:         )
   ...:     ]
   ...: )
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call
last)
Cell In[9], line 3
      1 m.ColumnarAttributesMeta(
      2     columns=[
----> 3         m.AttributesColumn(
      4             key="foo",
      5             type=m.ColumnType.ENUM,
      6         )
      7     ]
      8 )

File ~/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/pydantic/main.py:165,
in BaseModel.__init__(__pydantic_self__, **data)
    163 # `__tracebackhide__` tells pytest and some other tools to omit
this function from tracebacks
    164 __tracebackhide__ = True
--> 165 __pydantic_self__.__pydantic_validator__.validate_python(data,
self_instance=__pydantic_self__)

ValidationError: 1 validation error for AttributesColumn
  Value error, Enum columns must specify the enum values
[type=value_error, input_value={'key': 'foo', 'type': <ColumnType.ENUM:
'enum'>}, input_type=dict]
    For further information visit
https://errors.pydantic.dev/2.3/v/value_error

In [10]: m.ColumnarAttributesMeta(
    ...:     columns=[
    ...:         m.AttributesColumn(
    ...:             key="foo",
    ...:             type=m.ColumnType.ENUM,
    ...:             enum_values=["foo", "bar"]
    ...:         )
    ...:     ]
    ...: )
Out[10]: ColumnarAttributesMeta(columns=[AttributesColumn(key='foo',
type=<ColumnType.ENUM: 'enum'>, filter_strategy=None, min_value=None,
max_value=None, enum_values=['foo', 'bar'])])
```